[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vesting = "BH6VL6pHv4G1xpd13nWjKh6NuAVNG8hgYrxu3Q464Bax"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
